### ISSUE TITLE
Bots just thinking

### ISSUE THREAD

**Issue by TopClips** [boxsux/reactionfirst-bot#2]
![Uploading 42E424AA-1CA4-4F31-ADDE-990E7B080578.png…]()

**Comment by angelyurii** [comment]
Hey there! Just pushed a new commit to the main branch and your issue should be fixed. I'm closing this issue, but feel free to re-open it if you still experience this issue! :)

(To grab the changes, run `git pull` in the folder you cloned the bot in. If you made any changes to the main files yourself, stash your changes with `git stash` first!)
